import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Next Chat</h1>
      </header>
      <div className="content">
        <aside>
          <div>
            <button>DM</button>
          </div>
          <ul>
            <li>
              <button>Room1</button>
            </li>
            <li>
              <button>Room2</button>
            </li>
            <li>
              <button>Room3</button>
            </li>
            <li>
              <button>Room4</button>
            </li>
          </ul>
        </aside>
        <main className={styles.main}>
          <div>
            <h2>
              <span>ダイレクトメッセージ</span>
              <button>+</button>
            </h2>
            <ul>
              <li>
                <a href="#">
                  <Image
                    src="./icon/icon_seal.svg"
                    alt=""
                    width="80"
                    height="80"
                  />
                </a>
                <button>×</button>
              </li>
            </ul>
          </div>
          <div>
            <div>
              <p>message</p>
              <p>message</p>
              <p>message</p>
              <p>message</p>
              <p>message</p>
              <p>message</p>
              <p>message</p>
            </div>
            <div>profile area</div>
          </div>
        </main>
      </div>
      <footer>
        icon download from&ensp;
        <a href="http://flat-icon-design.com/?tag=animal">here</a>
      </footer>
    </>
  );
}
